#!/bin/bash

case $BUTTON in 
  1) notify-send "volume 1";;
  2) notify-send "volume 2";;
  3) notify-send "volume 3";;
esac

barcolor=#11111A
widgetcolor=#A6DA95
panelcolor=#1E2030

if [[ $1 ]]
then
  printf "^b$widgetcolor^^c$barcolor^ "
  printf "󰕾"
else
  printf "^c$widgetcolor^^b$panelcolor^ "
  amixer sget Master | awk -F"[][]" '/Left:/ { print $2 }'
fi

