#!/bin/bash

case $BUTTON in 
  1) ~/.config/rofi/menus/shutdown.sh;;
  # 2) notify-send "power 2";;
  # 3) notify-send "power 3";;
esac

barcolor=#11111A
widgetcolor=#ED8796

printf "^c$widgetcolor^^b$barcolor^  "
