#!/bin/bash

spawn_calendar() {
	gnome-calendar &
	pid=''
	while [[ -z $pid ]]; do
		pid=$(xdotool search --onlyvisible --class gnome-calendar | grep -Eo '[0-9]+')
	done
	xdotool windowmove $pid 2670 20
}

case $BUTTON in
1) spawn_calendar ;;
	# 2) notify-send "clock 2";;
	# 3) notify-send "clock 3";;
esac

barcolor=#141110
widgetcolor=#9cb7c4

if [[ $1 ]]; then
	printf "^c$widgetcolor^^b$barcolor^ "
	printf "󰃰"
else
	printf "^c$widgetcolor^^b$barcolor^ "
	date "+%d %a %H:%M"
fi
